config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  resources :boards
  # resources :departures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  def departures
    Departure.where origin: self.location
  end
end

app/models/departure.rb
class Departure < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    DepartureFetcher.call
    @departures = @board.departures
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:location)
    end
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  before_action :set_departure, only: [:show, :edit, :update, :destroy]

  # GET /departures
  # GET /departures.json
  def index
    @departures = Departure.all
  end

  # GET /departures/1
  # GET /departures/1.json
  def show
  end

  # GET /departures/new
  def new
    @departure = Departure.new
  end

  # GET /departures/1/edit
  def edit
  end

  # POST /departures
  # POST /departures.json
  def create
    @departure = Departure.new(departure_params)

    respond_to do |format|
      if @departure.save
        format.html { redirect_to @departure, notice: 'Departure was successfully created.' }
        format.json { render :show, status: :created, location: @departure }
      else
        format.html { render :new }
        format.json { render json: @departure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departures/1
  # PATCH/PUT /departures/1.json
  def update
    respond_to do |format|
      if @departure.update(departure_params)
        format.html { redirect_to @departure, notice: 'Departure was successfully updated.' }
        format.json { render :show, status: :ok, location: @departure }
      else
        format.html { render :edit }
        format.json { render json: @departure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departures/1
  # DELETE /departures/1.json
  def destroy
    @departure.destroy
    respond_to do |format|
      format.html { redirect_to departures_url, notice: 'Departure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departure
      @departure = Departure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departure_params
      params.require(:departure).permit(:time_stamp, :origin, :trip, :destination, :scheduled_time, :lateness, :track, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/departures_helper.rb
module DeparturesHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :board_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<% @boards.each do |board| %>
  <h1><%= link_to board.location, board %></h1>
<% end %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @board.location %></h1>

<%= render partial: 'departures/list' %>

<i><%= link_to 'Back', boards_path %></i>

app/views/departures/_form.html.erb
<%= form_with(model: departure, local: true) do |form| %>
  <% if departure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departure.errors.count, "error") %> prohibited this departure from being saved:</h2>

      <ul>
      <% departure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :time_stamp %>
    <%= form.datetime_select :time_stamp, id: :departure_time_stamp %>
  </div>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :departure_origin %>
  </div>

  <div class="field">
    <%= form.label :trip %>
    <%= form.text_field :trip, id: :departure_trip %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, id: :departure_destination %>
  </div>

  <div class="field">
    <%= form.label :scheduled_time %>
    <%= form.datetime_select :scheduled_time, id: :departure_scheduled_time %>
  </div>

  <div class="field">
    <%= form.label :lateness %>
    <%= form.number_field :lateness, id: :departure_lateness %>
  </div>

  <div class="field">
    <%= form.label :track %>
    <%= form.text_field :track, id: :departure_track %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :departure_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departures/_list.html.erb
<table>
  <tr>
    <th>Time Stamp</th>
    <th>Origin</th>
    <th>Trip</th>
    <th>Destination</th>
    <th>Scheduled Time</th>
    <th>Lateness</th>
    <th>Track</th>
    <th>Status</th>
  </tr>

  <% @departures.each do |dep| %>
    <tr>
      <td><%= dep.time_stamp %></td>
      <td><%= dep.origin %></td>
      <td><%= dep.trip %></td>
      <td><%= dep.destination %></td>
      <td><%= dep.scheduled_time %></td>
      <td><%= dep.lateness %></td>
      <td><%= dep.track %></td>
      <td><%= dep.status %></td>
    </tr>
  <% end %>
</table>

app/views/departures/edit.html.erb
<h1>Editing Departure</h1>

<%= render 'form', departure: @departure %>

<%= link_to 'Show', @departure %> |
<%= link_to 'Back', departures_path %>

app/views/departures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departures</h1>

<table>
  <thead>
    <tr>
      <th>Time stamp</th>
      <th>Origin</th>
      <th>Trip</th>
      <th>Destination</th>
      <th>Scheduled time</th>
      <th>Lateness</th>
      <th>Track</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departures.each do |departure| %>
      <tr>
        <td><%= departure.time_stamp %></td>
        <td><%= departure.origin %></td>
        <td><%= departure.trip %></td>
        <td><%= departure.destination %></td>
        <td><%= departure.scheduled_time %></td>
        <td><%= departure.lateness %></td>
        <td><%= departure.track %></td>
        <td><%= departure.status %></td>
        <td><%= link_to 'Show', departure %></td>
        <td><%= link_to 'Edit', edit_departure_path(departure) %></td>
        <td><%= link_to 'Destroy', departure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departure', new_departure_path %>

app/views/departures/new.html.erb
<h1>New Departure</h1>

<%= render 'form', departure: @departure %>

<%= link_to 'Back', departures_path %>

app/views/departures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time stamp:</strong>
  <%= @departure.time_stamp %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @departure.origin %>
</p>

<p>
  <strong>Trip:</strong>
  <%= @departure.trip %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @departure.destination %>
</p>

<p>
  <strong>Scheduled time:</strong>
  <%= @departure.scheduled_time %>
</p>

<p>
  <strong>Lateness:</strong>
  <%= @departure.lateness %>
</p>

<p>
  <strong>Track:</strong>
  <%= @departure.track %>
</p>

<p>
  <strong>Status:</strong>
  <%= @departure.status %>
</p>

<%= link_to 'Edit', edit_departure_path(@departure) %> |
<%= link_to 'Back', departures_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Departures</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>